---
title: 'Example: IVD'
subtitle: "SROC"
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document:
editor_options:
  chunk_output_type: console
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="", fig.width = 10, fig.height = 10)
options(knitr.kable.NA = "")

rm(list = ls())
library(knitr)
library(kableExtra)
library(latex2exp)
library(mvmeta)

files.sources = list.files("functions/")
sapply(paste0("functions/", files.sources), source)

data <- read.csv("data-IVD.csv")

## WHETHER TO SAVE PLOTS AND TABLES

save.results <- FALSE

sauc.type <- "sroc"

```

# IVD 

```{r, include=FALSE}
## SET SELECTION PROBABILITY p 

p.seq <- c(1, 0.8, 0.6, 0.4)

## ESITMATION WHEN WE TREAT c1, c2 AS PARAMETERS

est2 <- sapply(p.seq, function(p) {
  
  ## ESTIMATES OF THE PARAMETERS
  
  opt2 <- dtametasa.rc(data, p, c1.sq.init = 0.5, beta.interval = c(0,2), sauc.type = sauc.type)

  c(conv = opt2$convergence, opt2$sauc.ci, opt2$mu1.ci[4:6], opt2$mu2.ci[4:6], opt2$beta.ci, opt2$alpha, opt2$par)
  
})



## ESITMATION WHEN WE SET c1 = c2

est11 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p = 0.8, c1.sq = 0.5, beta.interval = c(0,2), sauc.type = sauc.type)
  
  c(conv = opt1$convergence, opt1$sauc.ci, opt1$mu1.ci[4:6], opt1$mu2.ci[4:6], opt1$beta.ci, opt1$alpha, opt1$par, c1 = sqrt(0.5))
  
  })


## ESITMATION WHEN WE SET c1 = 1, c2 = 0

est10 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p, c1.sq = 1, beta.interval = c(0,2), sauc.type = sauc.type)
  
  c(conv = opt1$convergence, opt1$sauc.ci, opt1$mu1.ci[4:6], opt1$mu2.ci[4:6], opt1$beta.ci, opt1$alpha, opt1$par, c1 = sqrt(1))
  
})


## ESITMATION WHEN WE SET c1 = 0, c2 = 1

est01 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p, c1.sq = 0, beta.interval = c(0,2), sauc.type = sauc.type)
  
  c(conv = opt1$convergence, opt1$sauc.ci, opt1$mu1.ci[4:6], opt1$mu2.ci[4:6], opt1$beta.ci, opt1$alpha, opt1$par, c1 = sqrt(0))
  
})


## ALL RESULTS

colnames(est2)<- paste0("p = ", p.seq)

colnames(est11)<- paste0("p = ", p.seq)

colnames(est10)<- paste0("p = ", p.seq)

colnames(est01)<- paste0("p = ", p.seq)




```



# PLOT: SROC curve

```{r, fig.width=10, fig.height=10}
# PLEASE CHOOSE ONE SAVED DATA *******


se <- data$TP/(data$TP+data$FN)
sp <- data$TN/(data$TN+data$FP)





par(mfrow = c(2, 2))

# col <- gray.colors(10, gamma = 1, start = 0, end = 0.8)
col <- 1:4

plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "FPR", ylab = "TPR")
# text(1-sp, se, labels=data$cutoff, cex=0.9, font=2)
sROC(est2.par, add = TRUE, ncols = col, sroc.type = sauc.type)
legend("bottomright", 
       bty='n',
       # legend = c(sprintf("p = %.1f, SAUC = %.3f",  p.seq[1], est2[10,1]),
       #            #TeX(sprintf("$(\\hat{c}_1, \\, \\hat{c}_2) = (-, -)$", est2[6,1], est2[7,1])),
       #            sprintf("p = %.1f, SAUC = %.3f",  p.seq[2], est2[10,2]),
       #            TeX(sprintf("$(\\hat{c}_1, \\, \\hat{c}_2) = (%.3f, %.3f)$", est2[6,2], est2[7,2])),
       #            sprintf("p = %.1f, SAUC = %.3f",  p.seq[3], est2[10,3]),
       #            TeX(sprintf("$(\\hat{c}_1, \\, \\hat{c}_2) = (%.3f, %.3f)$", est2[6,3], est2[7,3])),
       #            sprintf("p = %.1f, SAUC = %.3f",  p.seq[4], est2[10,4]),
       #            TeX(sprintf("$(\\hat{c}_1, \\, \\hat{c}_2) = (%.3f, %.3f)$", est2[6,4], est2[7,4]))
       #            ), 
       legend = c(sprintf("p = %.1f, SAUC = %.3f", p.seq, est2[8, ])), 
       col = col, pch = 18, pt.cex = 2, cex = 1.2, 
       lty = rep(1,3))
title("(A)", adj = 0, font.main = 1, cex.main = 1.5)
title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = 1.5)

      
plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "FPR", ylab = "TPR")
sROC(est11[c(1:5),  ], add = TRUE, ncols = col, sroc.type = sauc.type)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.1f, SAUC = %.3f", p.seq, est11[7, ])), 
       col = col, pch = 18, pt.cex = 2, cex = 1.2, 
       lty = rep(1,3))
title("(B)", adj = 0, font.main = 1, cex.main = 1.5)
title(TeX("$(c_1, \\,c_2) = (1/\\sqrt{2}, 1/\\sqrt{2})$"), cex.main = 1.5)



plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "FPR", ylab = "TPR")
sROC(est10[c(1:5),  ], add = TRUE, ncols = col, sroc.type = sauc.type)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.1f, SAUC = %.3f", p.seq, est10[7, ])), 
       col = col, pch = 18, pt.cex = 2, cex = 1.2, 
       lty = rep(1,3))
title("(C)", adj = 0, font.main = 1, cex.main = 1.5)
title(TeX("$(c_1,\\, c_2) = (1,\\, 0)$"), cex.main = 1.5)


plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "FPR", ylab = "TPR")
sROC(est01[c(1:5),  ], add = TRUE, ncols = col, sroc.type = sauc.type)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.1f, SAUC = %.3f", p.seq, est01[7, ])), 
       col = col, pch = 18, pt.cex = 2, cex = 1.2, 
       lty = rep(1,3))
title("(D)", adj = 0, font.main = 1, cex.main = 1.5)
title(TeX("$(c_1,\\, c_2) = (0,\\, 1)$"), cex.main = 1.5)

par(mfrow = c(1,1))

if(save.results) dev.off()
```


# PLOT: Probit of $\alpha$ and $\beta$

```{r, fig.width=10, fig.height=6}

ldata <- logit.data(correction(data))

t11 <- (ldata$y1 + ldata$y2)/sqrt(ldata$v1+ldata$v2)
t10 <- (ldata$y1 )/sqrt(ldata$v1)
t01 <- (ldata$y2)/sqrt(ldata$v2)


# Plot
if(save.results) {setEPS(width = 10, height = 5); postscript("ivd-p.eps")}

par(mfrow = c(2, 2))
curve(pnorm(est2[8,2]*x + est2[9,2]), -5, 15, ylim = c(0,1),
      xlab = ("t"), ylab = TeX("$p = \\Phi(\\beta \\, t + \\alpha)$"), col=2,
      yaxt='n')
axis(2, at=c(0,0.5,1), labels = c(0,0.5,1))
curve(pnorm(est2[8,3]*x + est2[9,3]), -5, 15, add = TRUE, col=3)
curve(pnorm(est2[8,4]*x + est2[9,4]), -5, 15, add = TRUE, col=4)
t02 <- (est2[6,2]*ldata$y1 + est2[7,2]*ldata$y2)/sqrt(est2[6,2]*ldata$v1+est2[7,2]*ldata$v2)
t03 <- (est2[6,3]*ldata$y1 + est2[7,3]*ldata$y2)/sqrt(est2[6,3]*ldata$v1+est2[7,3]*ldata$v2)
t04 <- (est2[6,4]*ldata$y1 + est2[7,4]*ldata$y2)/sqrt(est2[6,4]*ldata$v1+est2[7,4]*ldata$v2)
points(t02, rep(0.2, length(t02)), pch="|", col=2, cex=0.7)
points(t03, rep(0.1, length(t03)), pch="|", col=3, cex=0.7)
points(t04, rep(0,   length(t04)), pch="|", col=4, cex=0.7)

title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = 1.5)
legend("topright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", p.seq[-1])), 
       col = 2:4, cex = 1.2, 
       lty = rep(1,3))
title("(A)", adj = 0, font.main = 1, cex.main = 1.5)

# legend("topright", 
#        bty='n',
#        legend = c(
#          sprintf("p = %.2f", p.seq[2]), 
#          TeX(sprintf("$(\\hat{c}_1, \\, \\hat{c}_2) = (%.3f, %.3f)$",est2[6, 2], est2[7, 2])),
#          sprintf("p = %.2f", p.seq[3]),
#          TeX(sprintf("$(\\hat{c}_1, \\, \\hat{c}_2) = (%.3f, %.3f)$", est2[6, 3], est2[7, 3])),
#          sprintf("p = %.2f", p.seq[4]),
#          TeX(sprintf("$(\\hat{c}_1, \\, \\hat{c}_2) = (%.3f, %.3f)$", est2[6, 4], est2[7, 4]))
#          ),
#        col = c(2, NA, 3, NA, 4, NA), cex = 1, 
#        lty = c(1, NA, 1, NA, 1, NA))


curve(pnorm(est11[8,2]*x + est11[9,2]), -5, 15,ylim = c(0,1),
      xlab = ("t"), ylab = TeX("$p = \\Phi(\\beta \\, t + \\alpha)$"), col=2,
      yaxt='n')
axis(2, at=c(0,0.5,1), labels = c(0,0.5,1))
curve(pnorm(est11[8,3]*x + est11[9,3]), -5, 15, add = TRUE, col=3)
curve(pnorm(est11[8,4]*x + est11[9,4]), -5, 15, add = TRUE, col=4)
points(t11, rep(0, length(t11)), pch="|", cex=0.7)
title(TeX("$(c_1, \\,c_2) = (1/\\sqrt{2}, 1/\\sqrt{2})$"), cex.main = 1.5)
legend("topright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", p.seq[-1])), 
       col = 2:4, cex = 1.2, 
       lty = rep(1,3))
title("(B)", adj = 0, font.main = 1, cex.main = 1.5)




curve(pnorm(est10[8,2]*x + est10[9,2]), -5, 15,ylim = c(0,1),
      xlab = ("t"), ylab = TeX("$p = \\Phi(\\beta \\, t + \\alpha)$"), col=2,
      yaxt='n')
axis(2, at=c(0,0.5,1), labels = c(0,0.5,1))
curve(pnorm(est10[8,3]*x + est10[9,3]), -5, 15, add = TRUE, col=3)
curve(pnorm(est10[8,4]*x + est10[9,4]), -5, 15, add = TRUE, col=4)
points(t10, rep(0, length(t10)), pch="|", cex=0.7)
title(TeX("$(c_1, \\,c_2) = (1, \\,0)$"), cex.main = 1.5)
legend("topright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", p.seq[-1])), 
       col = 2:4, cex = 1.2, 
       lty = rep(1,3))
title("(C)", adj = 0, font.main = 1, cex.main = 1.5)



curve(pnorm(est01[8,2]*x + est01[9,2]), -5, 15, ylim = c(0,1),
      xlab = ("t"), ylab = TeX("$p = \\Phi(\\beta \\, t + \\alpha)$"), col=2,
      yaxt='n')
axis(2, at=c(0,0.5,1), labels = c(0,0.5,1))
curve(pnorm(est01[8,3]*x + est01[9,3]), -5, 15, add = TRUE, col=3)
curve(pnorm(est01[8,4]*x + est01[9,4]), -5, 15, add = TRUE, col=4)
points(t01, rep(0, length(t01)), pch="|", cex=0.7)
title(TeX("$(c_1, \\,c_2) = (0, \\,1)$"), cex.main = 1.5)
legend("topright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", p.seq[-1])), 
       col = 2:4, cex = 1.2, 
       lty = rep(1,3))
title("(D)", adj = 0, font.main = 1, cex.main = 1.5)


par(mfrow = c(1, 1))

if(save.results) dev.off()


```


# TABLE: Estimates 

## Table 1


```{r}


reform.est <- function(est){

 est <- est2
est.m <- est[c(1:9, 11:12),]
sauc.ci <- sprintf("%.3f (%.3f, %.3f)", est[10,], est[13,], est[14,])
b.ci    <- sprintf("%.3f (%.3f, %.3f)", est[8, ], est[15,], est[16,])
se.ci   <- sprintf("%.3f (%.3f, %.3f)", est[11,], est[17,], est[18,])
sp.ci   <- sprintf("%.3f (%.3f, %.3f)", est[12,], est[19,], est[20,])

tb <- data.frame(p.seq=p.seq, 
                 sauc.ci= sauc.ci, 
                 t(est.m)[,1:7], 
                 b.ci = b.ci, 
                 a = t(est.m)[,9],
                 se.ci = se.ci,
                 sp.ci = sp.ci)#[, -c(8:9, 13:14, 18:19)]

colnames(tb) <- c("$p$", "SAUC (95\\%CI)",
                  "$\\mu_1$", "$\\mu_2$", "$\\tau_1$","$\\tau_2$","$\\rho$",
                  "$c_1$", "$c_2$", "$\\beta$ (95\\%CI)", "$\\alpha_p$", "Se (95\\%CI)", "Sp (95\\%CI)"
                  )
rownames(tb) <- NULL

tb

}

tb2  <- reform.est(est2)

tb11 <- reform.est(est11)
tb10 <- reform.est(est10)
tb01 <- reform.est(est01)

tb1 <- rbind(tb2, tb11, tb10, tb01)
tb1[5:16, 8:9] <- NA
tb1[c(1,5,9,13), 10] <- NA


tb2 <- cbind("$(c_1, \\,c_2)$" = c("$(\\hat{c}_1, \\hat{c}_2)$", rep("", 3),
                            "$(0.7, 0.7)$", rep("",3),
                            "$(1, 0)$", rep("", 3),
                            "$(0, 1)$", rep("", 3)),
             tb1)

if(save.results) sink("tb-ivd-c.tex")

kbl(tb2, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits = 3,
    align = "r",
    linesep = c(rep("",3), "\\addlinespace"),
    escape = FALSE,
    caption = "Example: IVD")%>%
  kable_styling(latex_options = "scale_down")

if(save.results) sink()

```


## Table 2 (without c)


```{r}


reform.est <- function(est){

# est <- est2
est.m <- est[c(1:9, 11:12),]
sauc.ci <- sprintf("%.3f (%.3f, %.3f)", est[10,], est[13,], est[14,])
b.ci    <- sprintf("%.3f (%.3f, %.3f)", est[8, ], est[15,], est[16,])
se.ci   <- sprintf("%.3f (%.3f, %.3f)", est[11,], est[17,], est[18,])
sp.ci   <- sprintf("%.3f (%.3f, %.3f)", est[12,], est[19,], est[20,])

tb <- data.frame(p.seq=p.seq, 
                 sauc.ci= sauc.ci, 
                 t(est.m)[,1:5], 
                 b.ci = b.ci, 
                 a = t(est.m)[,9],
                 se.ci = se.ci,
                 sp.ci = sp.ci)#[, -c(8:9, 13:14, 18:19)]

colnames(tb) <- c("$p$", "SAUC (95\\%CI)",
                  "$\\mu_1$", "$\\mu_2$", "$\\tau_1$","$\\tau_2$","$\\rho$",
                  "$\\beta$ (95\\%CI)", "$\\alpha_p$", "Se (95\\%CI)", "Sp (95\\%CI)"
                  )
rownames(tb) <- NULL

tb

}

tb2  <- reform.est(est2)

tb11 <- reform.est(est11)
tb10 <- reform.est(est10)
tb01 <- reform.est(est01)

tb1 <- rbind(tb2, tb11, tb10, tb01)

tb1[c(1,5,9,13), 8] <- NA


tb2 <- cbind("$(c_1, \\,c_2)$" = c("$(\\hat{c}_1, \\hat{c}_2)$", rep("", 3),
                            "$(0.7, 0.7)$", rep("",3),
                            "$(1, 0)$", rep("", 3),
                            "$(0, 1)$", rep("", 3)),
             tb1)

if(save.results)  sink("tb-ivd.tex")

kbl(tb2, 
    format = "latex",
    longtable = F, 
    booktabs = T, 
    digits = 3,
    align = "r",
    linesep = c(rep("",3), "\\addlinespace"),
    escape = FALSE,
    caption = "Example: IVD")

if(save.results)  sink()

```

\newpage 

# PLOT: SAUC plot 

```{r, fig.height=10, fig.width=10}

p.seq <- seq(1, 0.1, -0.1)

## ESITMATION WHEN WE TREAT c1, c2 AS PARAMETERS

est2 <- sapply(p.seq, function(p) {
  
  ## ESTIMATES OF THE PARAMETERS
  opt2 <- dtametasa.rc(data, p, beta.interval = c(0,2))

  c(opt2$sauc.ci)
  
})



## ESITMATION WHEN WE SET c1 = c2

est11 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq =0.5, beta.interval = c(0,2))
  
  c(opt1$sauc.ci)
  
  })

est10 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq = 1, beta.interval = c(0,2))
  
  c(opt1$sauc.ci)
  
  })

est01 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq = 0, beta.interval = c(0,2))
  
  c(opt1$sauc.ci)
  
  })


## ALL RESULTS

colnames(est2)<- paste0("p = ", p.seq)

colnames(est11)<- paste0("p = ", p.seq)

colnames(est10)<- paste0("p = ", p.seq)

colnames(est01)<- paste0("p = ", p.seq)

## Plot
if(save.results)  {setEPS(width = 9, height = 9); postscript("ivd-sauc.eps")}

par(mfrow = c(2,2))


matplot(t(est2),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "p", xaxt = "n")
title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = 1.5)
axis(1, at = 1:10, labels = p.seq)
abline(h=0.5, col="grey54", lty=2)
title("(A)", adj = 0, font.main = 1, cex.main = 1.5)


matplot(t(est11),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "p", xaxt = "n")
title(TeX("$(c_1, \\,c_2) = (1/\\sqrt{2}, 1/\\sqrt{2})$"), cex.main = 1.5)
axis(1, at = 1:10, labels = p.seq)
abline(h=0.5, col="grey54", lty=2)
title("(B)", adj = 0, font.main = 1, cex.main = 1.5)


matplot(t(est10),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "p", xaxt = "n")
title(TeX("$(c_1, \\,c_2) = (1, \\,0)$"), cex.main = 1.5)
axis(1, at = 1:10, labels = p.seq)
abline(h=0.5, col="grey54", lty=2)
title("(C)", adj = 0, font.main = 1, cex.main = 1.5)


matplot(t(est01),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "p", xaxt = "n")
title(TeX("$(c_1, \\,c_2) = (0, \\,1)$"), cex.main = 1.5)
axis(1, at = 1:10, labels = p.seq)
# title("(b)", adj = 0, font.main = 1)
abline(h=0.5, col="grey54", lty=2)
title("(D)", adj = 0, font.main = 1, cex.main = 1.5)


par(mfrow = c(1,1))

if(save.results)  dev.off()
```




