---
title: "Estimates of Parameters ($c_1=0, c_2=1$)"
subtitle: "$(\\tau_1^2, \\tau_2^2) = (0.5, 0.5)$"
author: "Yi"
date: "`r format(Sys.Date())`"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="", fig.pos = "H")
options(knitr.kable.NA = "")
library(kableExtra)

  
table.pars <- function(list.n, row.n){
  
  load(s.rdt)
  # 
  # list.n <- 1
  # row.n  <- 1
  
  S <- set[[list.n]][row.n, 1]

  load(paste0(dt, "/sim_l", list.n, "_r",row.n, ".RData"))

  dim1 <- nrow(DATA)
  dim2 <- ncol(DATA)/1000
    
  name.c <- colnames(DATA)[1:dim2]

  dim(DATA) <- c(dim1, dim2, 1000)

  true.par <- c(set[[list.n]][row.n, ][c(2:3)],       # u1 u2
                sqrt(set[[list.n]][row.n, ][c(4:5)]), # t1 t2
                set[[list.n]][row.n, ][c(12)],        # r
                set[[list.n]][row.n, ][c(9:10)],      # b a
                sqrt(set[[list.n]][row.n, ][c(7)])
  )   

  med  <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))[1:8,] # -true.par
  iq25 <- apply(DATA, 1:2, function(x) quantile(x, prob =0.25, na.rm = TRUE))[1:8,]
  iq75 <- apply(DATA, 1:2, function(x) quantile(x, prob =0.75, na.rm = TRUE))[1:8,]

  X <- cbind.data.frame(true.par, 
                        med.sa2   = sprintf("%.3f (%.3f, %.3f)", med[,1], iq25[,1], iq75[,1]),
                        med.sa1.c = sprintf("%.3f (%.3f, %.3f)", med[,2], iq25[,2], iq75[,2]),
                        med.sa1.w = sprintf("%.3f (%.3f, %.3f)", med[,3], iq25[,3], iq75[,3]),
                        med.heck  = sprintf("%.3f (%.3f, %.3f)", med[,4], iq25[,4], iq75[,4]),
                        med.BRE   = sprintf("%.3f (%.3f, %.3f)", med[,5], iq25[,5], iq75[,5]),
                        med.BRE.p = sprintf("%.3f (%.3f, %.3f)", med[,6], iq25[,6], iq75[,6]) )
  
  conv1 <- DATA[9,1, ]
  conv2 <- DATA[9,2, ]
  conv3 <- DATA[9,3, ]
  conv4 <- DATA[9,4, ]
  conv5 <- DATA[9,5, ]
  conv6 <- DATA[9,6, ]

  conv.per <- c(NA, sum(conv1 %in% 0)/10, sum(conv2 %in% 0)/10, sum(conv3 %in% 0)/10,
                sum(conv4 %in% 0)/10, sum(conv5 %in% 0)/10, sum(conv6 %in% 0)/10)
  
  X[6:8,5:7] <- NA
  X[8,3:4] <- NA
  X <- rbind(X, conv.per)
  X
}
```


# Set Path

```{r, echo=TRUE}

# s.rdt <- "../../scenarios/scenarios-t0.7/set-t0.7-c11.RData"
# dt <- "c11"


# s.rdt <- "../../scenarios/scenarios-t0.7/set-t0.7-c10.RData"
# dt <- "c10"

 
s.rdt <- "../../scenarios/scenarios-t0.7/set-t0.7-c01.RData"
dt <- "c01"

```


# Scenarios

```{r}
load(s.rdt)

x <- set[[1]]
rownames(x) <- 1:6
colnames(x) <- c("S", "$\\mu_1$", "$\\mu_2$", "$\\tau_1^2$", "$\\tau_2^2$", "$\\tau_{12}$", "$c_1^2$", "$c_2^2$",
                 "$\\beta$", "$\\alpha$", "SAUC", "$\\rho$",  "Se", "Sp")

kbl(x, 
    format = "html",
    row.names = T,
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 2), '\\addlinespace'),
    escape = FALSE,
    caption = "Scenarios")%>% 
  kable_styling(full_width = TRUE)
```



# Results

**Note: results are shown as "median of the estimates - true values (lower, upper quartiles of the estimates)"**

$N = S\times p \approx S \times 0.7$

#### Scenario 1

```{r, results='asis'}


longtab <- rbind(table.pars(1, 1),
            table.pars(2, 1),
            table.pars(3, 1),
            table.pars(4, 1))

PAR <- rep(c("$\\mu_1$", "$\\mu_2$", "$\\tau_1$", "$\\tau_2$", "$\\rho$", 
         "$\\beta$", "$\\alpha$", "$c_1$", "CR"),4)

S <- c(10, rep(NA, 8), 15, rep(NA,8), 50, rep(NA,8), 200, rep(NA,8))
colnm <- c("$S$","Par","True", 
           "Proposed $(\\hat{c}_1^2, \\hat{c}_2^2)$",
           "Proposed (correct)",
           "Proposed (wrong)",
           "Heckman-type",
           "Reitsma$_O$", 
           "Reitsma$_P$")
longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm


# sink("supp-c10-tab2-1.tex")

kbl(longtab.f, 
    format = "html",
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters")%>% 
  kable_styling(full_width = TRUE)

# sink()
```

#### Scenario 2

```{r, results='asis'}


longtab <- rbind(table.pars(1, 2),
            table.pars(2, 2),
            table.pars(3, 2),
            table.pars(4, 2))

longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm

  
# sink("supp-c10-tab2-2.tex")

kbl(longtab.f, 
    format = "html",
    longtable = F, 
    booktabs = T, 
    digits = 3,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters")%>% 
  kable_styling(full_width = TRUE)
# sink()

```

#### Scenario 3

```{r, results='asis'}


longtab <- rbind(table.pars(1, 3),
            table.pars(2, 3),
            table.pars(3, 3),
            table.pars(4, 3))

longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm
 
# sink("supp-c10-tab2-3.tex")

kbl(longtab.f, 
    format = "html",
    longtable = F, 
    booktabs = T, 
    digits = 3,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters")%>% 
  kable_styling(full_width = TRUE)
# sink()

```


#### Scenario 4

```{r, results='asis'}


longtab <- rbind(table.pars(1, 4),
            table.pars(2, 4),
            table.pars(3, 4),
            table.pars(4, 4))


longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm
 
# sink("supp-c10-tab2-4.tex")

kbl(longtab.f, 
    format = "html",
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters")%>% 
  kable_styling(full_width = TRUE)
# sink()

```


#### Scenario 5

```{r, results='asis'}


longtab <- rbind(table.pars(1, 5),
            table.pars(2, 5),
            table.pars(3, 5),
            table.pars(4, 5))


longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm
 
# sink("supp-c10-tab2-4.tex")

kbl(longtab.f, 
    format = "html",
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters")%>% 
  kable_styling(full_width = TRUE)
# sink()

```


#### Scenario 6

```{r, results='asis'}


longtab <- rbind(table.pars(1, 6),
            table.pars(2, 6),
            table.pars(3, 6),
            table.pars(4, 6))


longtab.f <- cbind.data.frame(S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm
 
# sink("supp-c10-tab2-4.tex")

kbl(longtab.f, 
    format = "html",
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 7), '\\addlinespace'),
    escape = FALSE,
    caption = "Estimates of the parameters")%>% 
  kable_styling(full_width = TRUE)
# sink()

```


