---
title: "scenarioss Table"
author: "Yi"
date: "`r format(Sys.Date())`"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="")

options(knitr.kable.NA = " ")
library(kableExtra)

save.result <- FALSE
# save.result <- TRUE
```

# $(\tau_1^2, \tau_2^2) = (1, 4)$

```{r}
load("scenarios-t12/set-t12-c11.RData")
set1 <- set[[1]][c(1:6), c(11, 2:6, 12, 9, 10)]

load("scenarios-t12/set-t12-c10.RData")
set2 <- set[[1]][c(1:6), c(10)]

load("scenarios-t12/set-t12-c01.RData")
set3 <- set[[1]][c(1:6), c(10)]

id <- 1:6

scen <- cbind.data.frame(id, set1, set2, set3)
colnames(scen) <- c("No.", "SAUC", 
                    "$\\mu_1$", "$\\mu_2$", "$\\tau_1^2$", "$\\tau_2^2$", "$\\tau_{12}$", 
                    "$\\rho$", "$\\beta$", "$\\alpha_{0.7}$", "$\\alpha_{0.7}$", "$\\alpha_{0.7}$")
rownames(scen) <- NULL



if(save.result) sink("../../../Manu1/SIM-2/SIM-ver2-1221/tab/tb-scenarios-t12.tex")

kbl(scen, 
    format = ifelse(save.result, "latex", "html"),
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = "",
    escape = FALSE,
    caption = "Scenarios for simulation studies given $p \\approx 0.7$",
    label = "sce12") %>% 
  add_header_above(c(rep(" ",9), "$c_1 = c_2$" = 1, "$c_1 = 1$" = 1, "$c_1 = 0$" = 1),
  																	escape = FALSE)

if(save.result) sink()

```


# $(\tau_1^2, \tau_2^2) = (0.5, 0.5)$


```{r}
load("scenarios-t0.7/set-t0.7-c11.RData")
set1 <- set[[1]][c(1:6), c(11, 2:6, 12, 9, 10)]

load("scenarios-t0.7/set-t0.7-c10.RData")
set2 <- set[[1]][c(1:6), c(10)]

load("scenarios-t0.7/set-t0.7-c01.RData")
set3 <- set[[1]][c(1:6), c(10)]

id <- 7:12

scen <- cbind.data.frame(id, set1, set2, set3)
colnames(scen) <- c("No.", "SAUC", 
                    "$\\mu_1$", "$\\mu_2$", "$\\tau_1^2$", "$\\tau_2^2$", "$\\tau_{12}$", 
                    "$\\rho$", "$\\beta$", "$\\alpha_{0.7}$", "$\\alpha_{0.7}$", "$\\alpha_{0.7}$")
rownames(scen) <- NULL





if(save.result) sink("../../../Manu1/SIM-2/SIM-ver2-supp-1221/tab/tb-scenarios-t0.5.tex")

kbl(scen, 
    format = ifelse(save.result, "latex", "html"),
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = "",
    escape = FALSE,
    caption = "Additional scenarios for simulation studies given $p \\approx 0.7$",
    label = "sceall") %>% 
  add_header_above(c(rep(" ",9), "$c_1 = c_2$" = 1, "$c_1 = 1$" = 1, "$c_1 = 0$" = 1),
  																	escape = FALSE)

if(save.result) sink()

```