---
title: "Estimates of Parameters ($c_1=1, c_2=0$)"
author: "Yi"
date: "`r format(Sys.Date())`"
output:
  pdf_document: default
  html_document: default
subtitle: $(\tau_1^2, \tau_2^2) = (1, 4)$
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="", fig.pos = "H")
options(knitr.kable.NA = "")
library(kableExtra)

  
table.pars <- function(list.n, row.n){
  
  load(s.rdt) 
  # 
  # list.n <- 1
  # row.n  <- 1
  
  S <- set[[list.n]][row.n, 1]

  load(paste0(dt, "/sim_l", list.n, "_r",row.n, ".RData"))

  dim1 <- nrow(DATA)
  dim2 <- ncol(DATA)/1000
    
  name.c <- colnames(DATA)[1:dim2]

  dim(DATA) <- c(dim1, dim2, 1000)

  true.par <- c(set[[list.n]][row.n, ][c(2:3)],       # u1 u2
                sqrt(set[[list.n]][row.n, ][c(4:5)]), # t1 t2
                set[[list.n]][row.n, ][c(12)]        # r
                # set[[list.n]][row.n, ][c(9:10)],      # b a
                # sqrt(set[[list.n]][row.n, ][c(7)])
  														)   # c1

  med  <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))[1:5,] # -true.par
  iq25 <- apply(DATA, 1:2, function(x) quantile(x, prob =0.25, na.rm = TRUE))[1:5,]
  iq75 <- apply(DATA, 1:2, function(x) quantile(x, prob =0.75, na.rm = TRUE))[1:5,]

  X <- cbind.data.frame(true.par, 
                        med.sa2   = sprintf("%.3f (%.3f, %.3f)", med[,1], iq25[,1], iq75[,1]),
                        med.sa1.c = sprintf("%.3f (%.3f, %.3f)", med[,2], iq25[,2], iq75[,2]),
                        med.sa1.w = sprintf("%.3f (%.3f, %.3f)", med[,3], iq25[,3], iq75[,3]),
                        med.heck  = sprintf("%.3f (%.3f, %.3f)", med[,4], iq25[,4], iq75[,4]),
                        med.BRE   = sprintf("%.3f (%.3f, %.3f)", med[,5], iq25[,5], iq75[,5]),
                        med.BRE.p = sprintf("%.3f (%.3f, %.3f)", med[,6], iq25[,6], iq75[,6]) )
  
  # conv1 <- DATA[9,1, ]
  # conv2 <- DATA[9,2, ]
  # conv3 <- DATA[9,3, ]
  # conv4 <- DATA[9,4, ]
  # conv5 <- DATA[9,5, ]
  # conv6 <- DATA[9,6, ]
  # 
  # conv.per <- c(NA, sum(conv1 %in% 0)/10, sum(conv2 %in% 0)/10, sum(conv3 %in% 0)/10,
  #               sum(conv4 %in% 0)/10, sum(conv5 %in% 0)/10, sum(conv6 %in% 0)/10)
  # 
  # X[6:8,5:7] <- NA
  # X[8,3:4] <- NA
  # X <- rbind(X, conv.per)
  X
}
```


# Set Path

```{r, echo=TRUE}

# save.tex <- TRUE
save.tex <- TRUE; save.path <- "~/Documents/GitHub/Manu1/SIM/V4-0816/supp/tab/"


# s.rdt <- "../../scenarios/scenarios-t12/set-t12-c11.RData"
# dt <- "c11"


s.rdt <- "../../scenarios/scenarios-t12/set-t12-c10.RData"
dt <- "c10"

 
# s.rdt <- "../../scenarios/scenarios-t12/set-t12-c01.RData"
# dt <- "c01"

```


# Scenarios

```{r}
load(s.rdt)

x <- set[[1]]
rownames(x) <- 1:6
colnames(x) <- c("S", "$\\mu_1$", "$\\mu_2$", "$\\tau_1^2$", "$\\tau_2^2$", "$\\tau_{12}$", "$c_1^2$", "$c_2^2$",
                 "$\\beta$", "$\\alpha$", "SAUC", "$\\rho$",  "Se", "Sp")

kbl(x, 
    format = ifelse(save.tex, "latex", "html"),
    row.names = T,
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 2), '\\addlinespace'),
    escape = FALSE,
    caption = "Scenarios")%>% 
  kable_classic_2(full_width = TRUE)
```



# Results

**Note: results are shown as "median of the estimates - true values (lower, upper quartiles of the estimates)"**

$N = S\times p \approx S \times 0.7$

#### Scenario 1 & 2

```{r, results='asis'}


longtab <- rbind(
	table.pars(1, 1),
	table.pars(2, 1),
	table.pars(3, 1),
	table.pars(4, 1),
	table.pars(1, 2),
	table.pars(2, 2),
	table.pars(3, 2),
	table.pars(4, 2)	
)

PAR <- rep(c("$\\mu_1$", "$\\mu_2$", "$\\tau_1$", "$\\tau_2$", "$\\rho$"),8) 
         # "$\\beta$", "$\\alpha$", "$c_1$", "CR"),4)

S <- rep(c(15, rep(NA, 4), 25, rep(NA,4), 50, rep(NA,4), 200, rep(NA,4)),2)
No<- c(1, rep(NA, 19), 2, rep(NA,19))

colnm <- c("No.", "$S$","Par","True", 
           "Proposed $(\\hat{c}_1^2, \\hat{c}_2^2)$",
           "Proposed (correct)",
           "Proposed (wrong)",
           "Heckman-type",
           "Reitsma$_O$", 
           "Reitsma$_P$")
longtab.f <- cbind.data.frame(No = No, S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm


if (save.tex) sink(paste0(save.path, "tb-par1-t12-c10.tex"))

kbl(longtab.f, 
    format = ifelse(save.tex, "latex", "html"),
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 4), '\\addlinespace'),
    escape = FALSE,
				label = "c10-par1",
    caption = "Estimates of the parameters under the true selective publication mechanism of $(c_1, c_2) = (1,0)$ (Scenario No.1-2)")

if (save.tex)  sink()

```

#### Scenario 3 & 4

```{r, results='asis'}

longtab <- rbind(
	table.pars(1, 3),
	table.pars(2, 3),
	table.pars(3, 3),
	table.pars(4, 3),
	table.pars(1, 4),
	table.pars(2, 4),
	table.pars(3, 4),
	table.pars(4, 4)	
)

No<- c(3, rep(NA, 19), 4, rep(NA,19))
longtab.f <- cbind.data.frame(No = No, S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm


if (save.tex) sink(paste0(save.path, "tb-par2-t12-c10.tex"))

kbl(longtab.f, 
    format = ifelse(save.tex, "latex", "html"),
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 4), '\\addlinespace'),
    escape = FALSE,
				label = "c10-par2",
    caption = "Estimates of the parameters under the true selective publication mechanism of $(c_1, c_2) = (1,0)$ (Scenario No.3-4)")

if (save.tex)  sink()


```

#### Scenario 5 & 6

```{r, results='asis'}


longtab <- rbind(
	table.pars(1, 5),
	table.pars(2, 5),
	table.pars(3, 5),
	table.pars(4, 5),
	table.pars(1, 6),
	table.pars(2, 6),
	table.pars(3, 6),
	table.pars(4, 6)	
)

No<- c(5, rep(NA, 19), 6, rep(NA,19))
longtab.f <- cbind.data.frame(No = No, S = S, PAR = PAR, longtab)

rownames(longtab.f) <- NULL
colnames(longtab.f) <- colnm


if (save.tex) sink(paste0(save.path, "tb-par3-t12-c10.tex"))

kbl(longtab.f, 
    format = ifelse(save.tex, "latex", "html"),
    longtable = F, 
    booktabs = T, 
    digits =3,
    align = "r",
    linesep = c(rep('', 4), '\\addlinespace'),
    escape = FALSE,
				label = "c10-par3",
    caption = "Estimates of the parameters under the true selective publication mechanism of $(c_1, c_2) = (1,0)$ (Scenario No.5-6)")

if (save.tex)  sink()

```


